[package]
name = "axhal"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS hardware abstraction layer, provides unified APIs for platform-specific operations"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axhal"
documentation = "https://arceos-org.github.io/arceos/axhal/index.html"

[features]
smp = ["axplat-x86-pc/smp", "axplat-aarch64-qemu-virt/smp"]
irq = ["linkme", "axplat-x86-pc/irq", "axplat-aarch64-qemu-virt/irq"]
fp_simd = ["axcpu/fp_simd", "axplat-x86-pc/fp_simd", "axplat-aarch64-qemu-virt/fp_simd"]
rtc = ["axplat-x86-pc/rtc", "axplat-aarch64-qemu-virt/rtc"]
paging = ["axalloc", "page_table_multiarch"]
tls = ["axcpu/tls"]
uspace = ["paging", "axcpu/uspace"]
myplat = []
default = []

[dependencies]
log = "=0.4.21"
cfg-if = "1.0"
kernel_guard = "0.1"
lazyinit = "0.2"
percpu = "0.2"
heapless = "0.8"
memory_addr = "0.3"
linkme = { version = "0.3.33", optional = true }
page_table_multiarch = { version = "0.5", optional = true }
axcpu = { git = "https://github.com/arceos-org/axcpu.git" }
axplat = { git = "https://github.com/arceos-org/axhal_crates.git" }
axlog = { workspace = true }
axconfig = { workspace = true }
axalloc = { workspace = true, optional = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
axplat-x86-pc = { git = "https://github.com/arceos-org/axhal_crates.git" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64-cpu = "10.0"
axplat-aarch64-qemu-virt = { git = "https://github.com/arceos-org/axhal_crates.git" }

[build-dependencies]
axconfig = { workspace = true }
